---
title: "0831"
author: "20173250 정경현"
date: '2020 8 31 '
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#data
```{r}

#실적데이터 
sj01 <- read.csv("C:/Users/jgh0208/Desktop/2020빅콘테스트/2020BIG/data/2020빅콘테스트 문제데이터(데이터분석분야-챔피언리그)_update_200818/01_제공데이터/2020 빅콘테스트 데이터분석분야-챔피언리그_2019년 실적데이터_v1_200818.csv")

#시청률데이터
schr01 <- read.csv("C:/Users/jgh0208/Desktop/2020빅콘테스트/2020BIG/data/2020빅콘테스트 문제데이터(데이터분석분야-챔피언리그)_update_200818/01_제공데이터/2020 빅콘테스트 데이터분석분야-챔피언리그_시청률 데이터.csv")

#날씨데이터
wt01 <- read.csv("C:/Users/jgh0208/Desktop/2020빅콘테스트/2020BIG/data/weather201901011231.csv")

head(sj01)
head(schr01)
head(wt01)

colnames(sj01)
colnames(schr01)
colnames(wt01)

sj01$방송일시 <- substr(sj01$방송일시,1,10)

ti <- rep(schr01$간대,366)

schr01$"timenumber" <- c(1:1441)
#install.packages("reshape")
#library(reshape)
#schrlm <- melt(schr01,id.vars = schr01$timenumber,measure.vas=2:ncol(schr01))

schr01 <- schr01[c(1:1440),]

```

#시청률과 시간과의 관계보기
```{r}
colnames(schr01) <- substr(colnames(schr01),2,11)
plot(schr01$`2019.01.01`,ylab = "",type="p",pch=19,col="red")
par(new=T)
plot(schr01$`2019.01.02`,ylab = "",type="p",pch=19,col="blue")
par(new=T)
plot(schr01$`2019.01.03`,ylab = "",type="p",pch=19,col="green")

#데이터연결하기(상관관계보기위한)
colnames(schr01) <- c("Time",rep("day",367))

schrl <- schr01[,c(1,2)]

for (i in 3:368) {
  schr <- schr01[,c(1,i)]
  schrl <- rbind(schrl,schr)
}

schrl$number <- rep(c(1:1440),367)


plot(schrl$number,schrl$day,ylab = "",type="p",pch=19,col="darkgreen",main="시간대별 시청률",xlab="시간대별")
#ti <- as.numeric(schrl$Time)
#cor(schrl$number,schrl$day)

noz <- ifelse(schr01$day==0,NA,schr01$day)
nozdf <- data.frame(schrl$number,noz)
ndf <- na.omit(nozdf)
#ndf <- nozdf[which(nozdf$noz==0),]
ndf$noz <- as.numeric(ndf$noz)
cor(ndf$schrl.number,ndf$noz)



```